spring.application.name=venteapp

# Database H2 (dev)
#spring.datasource.url=jdbc:h2:mem:ventedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
# PostgreSQL - Aiven
spring.datasource.url=jdbc:postgresql://pg-5f7cefc-rayenzaghdoudi6-272f.i.aivencloud.com:25297/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JPA

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT
app.jwt.secret=VenteAppSuperSecretKey2024!@#$%^&*()XYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Server
server.port=8085
server.error.include-message=always

# Logging
logging.level.com.venteapp=DEBUG
logging.level.org.springframework.security=WARN
