spring.application.name=venteapp

# Database H2 (dev)
spring.datasource.url=jdbc:h2:mem:ventedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=VenteAppSuperSecretKey2024!@#$%^&*()XYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Server
server.port=8085
server.error.include-message=always

# Logging
logging.level.com.venteapp=DEBUG
logging.level.org.springframework.security=WARN
